apiVersion: v2
name: tip-catalog
description: Helm Chart of the TIP Catalog for Apache Iceberg
version: 0.2.0
appVersion: 0.2.1
type: application
home: https://github.com/hansetag/iceberg-catalog
icon: https://hansetag.com/landing/logo-BLQxxCCG.png
maintainers:
  - name: Tobias
    url: https://github.com/twuebi
  - name: Christian
    url: https://github.com/c-thiel
keywords:
  - iceberg
  - catalog
  - tip
  - rest
  - lakehouse
dependencies:
  - name: postgresql
    version: 15.5.24
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
