helmWait: true
catalog:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    labels:
      foo: bar
    ingressClassName: nginx
    host: iceberg-catalog.local
    tls:
      enabled: true
      secretName: iceberg-catalog-tls
