helmWait: true
catalog:
  podSecurityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true

  containerSecurityContext:
    runAsNonRoot: true
    readOnlyRootFilesystem: true
